qbgetstats <- function(x,y){
  qbName <- readline(prompt = "Enter quarterback name: ")
  attempts <- readline(prompt = "Enter number of attempts: ")
  attempts = as.integer(attempts)
  completions <- readline(prompt = "Enter number of completions: ")
  completions = as.integer(completions)
  passingYards <- readline(prompt = "Enter number of passing yards: ")
  passingYards = as.integer(passingYards)
  passingTouchdowns <- readline(prompt = "Enter number of passing touchdowns: ")
  passingTouchdowns = as.integer(passingTouchdowns)
  interceptions <- readline(prompt = "Enter number of interceptions: ")
  interceptions = as.integer(interceptions)
  gamesPlayed <- readline(prompt = "Enter number of games played: ")
  qbYPA <- (passingYards/attempts)
  qbComp <- ((completions/attempts) * 100)
  qbRating <- ((((((completions/attempts) - .3) * 5) + (((passingYards/attempts)-3)*.25) + ((passingTouchdowns/attempts)*20) + ((2.375 - (interceptions/attempts)*25))) /6) * 100)
  print(paste0("quarterback: ",qbName))
  print(paste0("number of attempts: ",attempts))
  print(paste0("number of completions: ",completions))
  print(paste0("passing completion percentage: ",qbComp))
  print(paste0("total passing yards: ",passingYards))
  print(paste0("yards per attempt: ",qbYPA))
  print(paste0("total passing touchdowns: ",passingTouchdowns))
  print(paste0("total interceptions: ",interceptions))
  print(paste0("quarterback rating: ",qbRating))
  print(paste0("games played: ", gamesPlayed))
}
rbgetstats <- function(x,y){
  rbName <- readline(prompt = "Enter runningback name: ")
  rushAttempts <- readline(prompt = "Enter number of rushing attempts: ")
  rushAttempts = as.integer(rushAttempts)
  rushingYards <- readline(prompt = "Enter number of rushing yards: ")
  rushingYards = as.integer(rushingYards)
  rushingTouchdowns <- readline(prompt = "Enter number of rushing touchdowns: ")
  rushingTouchdowns = as.integer(rushingTouchdowns)
  fumbles <- readline(prompt = "enter number of fumbles: ")
  fumbles = as.integer(fumbles)
  gamesPlayed <- readline(prompt = "Enter number of games played: ")
  rushYPA <- (rushingYards/rushAttempts)
  print(paste0("runningback: ",rbName))
  print(paste0("rushing attempts: ",rushAttempts))
  print(paste0("total rushing Yards: ",rushingYards))
  print(paste0("yards per rushing attempt: ",rushYPA))
  print(paste0("total rushing touchdowns: ", rushingTouchdowns))
  print(paste0("total fumbles: ", fumbles))
  print(paste0("games played: ", gamesPlayed))
}
wrgetstats <- function(x,y){
  wrName <- readline(prompt = "Enter receiver name: ")
  targets <- readline(prompt = "Enter number of times targeted: ")
  targets = as.integer(targets)
  catchAttempts <- readline(prompt = "Enter number of receptions: ")
  catchAttempts = as.integer(catchAttempts)
  catchYards <- readline(prompt = "Enter number of receiving yards: ")
  catchYards = as.integer(catchYards)
  receivingTouchdowns <- readline(prompt = "Enter number of receiving touchdowns: ")
  receivingTouchdowns = as.integer(receivingTouchdowns)
  fumbles <- readline(prompt = "enter number of fumbles: ")
  fumbles = as.integer(fumbles)
  gamesPlayed <- readline(prompt = "Enter number of games played: ")
  YPC <- (catchYards/catchAttempts)
  cEffeciency <- ((catchAttempts/targets)*100)
  print(paste0("receiver: ",wrName))
  print(paste0("receptions: ",catchAttempts))
  print(paste0("times targeted: ",targets))
  print(paste0("reception rate: ",cEffeciency))
  print(paste0("total receiving Yards: ",catchYards))
  print(paste0("yards per catch: ",YPC))
  print(paste0("total receiving touchdowns: ", receivingTouchdowns))
  print(paste0("total fumbles: ", fumbles))
  print(paste0("games played: ", gamesPlayed))
}
